mod common;

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Mutex;

use common::Db;
use rlsspec::config::{self, Spec};

const EXAMPLE: &str = "examples/multitenant";
const TABLES: [&str; 4] = ["organizations", "memberships", "projects", "tasks"];

// Roles are cluster-wide: two tests creating them at once would race past the `if not exists`.
static SCHEMA: Mutex<()> = Mutex::new(());

/// The example's schema and policies, applied the way docker compose does: committed, before rlsspec runs.
fn example_db(extra: &[&str]) -> Db {
    let db = Db::new();
    let _guard = SCHEMA.lock().unwrap_or_else(|e| e.into_inner());
    for file in ["schema.sql", "policies.sql"].iter().chain(extra) {
        db.execute(&fs::read_to_string(format!("{EXAMPLE}/{file}")).unwrap());
    }
    db
}

fn run(db: &Db, expected_code: i32) -> String {
    let out = db.run(&format!("{EXAMPLE}/rlsspec.yaml"));
    assert_eq!(
        out.code,
        Some(expected_code),
        "stdout:\n{}\nstderr:\n{}",
        out.stdout,
        out.stderr
    );
    assert_eq!(out.stderr, "");
    for table in TABLES {
        assert_eq!(db.count(table), 0, "seed rows left in {table}");
    }
    out.stdout
}

#[test]
fn multitenant_example_is_green() {
    let db = example_db(&[]);
    insta::assert_snapshot!(run(&db, 0));
}

#[test]
fn multitenant_example_catches_the_broken_delete_policy() {
    let db = example_db(&["broken.sql"]);
    let out = run(&db, 1);
    let failures: Vec<&str> = out.lines().filter(|l| l.contains('✗')).collect();
    assert_eq!(failures.len(), 1, "{out}");
    insta::assert_snapshot!(out);
}

#[test]
fn multitenant_example_is_fully_covered() {
    let db = example_db(&[]);
    let out = db.rlsspec(&["cover", "-c", &format!("{EXAMPLE}/rlsspec.yaml")]);
    assert_eq!(out.code, Some(0), "{}", out.stderr);
    assert_eq!(out.stderr, "");
    insta::assert_snapshot!(out.stdout);
}

fn scratch(test: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR")).join(test);
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

#[test]
fn init_scaffolds_the_example_with_every_cell_todo() {
    let db = example_db(&[]);
    {
        let _guard = SCHEMA.lock().unwrap_or_else(|e| e.into_inner());
        db.execute(
            "do $$ begin
                 if not exists (select from pg_roles where rolname = 'app_auditor') then
                     create role app_auditor bypassrls;
                 end if;
             end $$;
             grant select on tasks to app_auditor;",
        );
    }
    let spec = scratch("init_example").join("rlsspec.yaml");
    let spec_arg = spec.to_str().unwrap();

    let out = db.rlsspec(&["init", "-o", spec_arg]);
    assert_eq!(out.code, Some(0), "{}", out.stderr);
    assert_eq!(out.stderr, "");
    assert_eq!(
        out.stdout,
        format!("wrote {spec_arg}: 4 tables × 2 identities, 32 cells todo\n")
    );
    let text = fs::read_to_string(&spec).unwrap();
    insta::assert_snapshot!(text);

    let url = db.url("postgres", "postgres");
    let env = |name: &str| (name == "DATABASE_URL").then(|| url.clone());
    let config = config::parse(&text, &spec, &env).unwrap();
    assert_eq!(config.expect.len(), 8);
    for block in &config.expect {
        let ops = &block.ops;
        assert_eq!(ops.select, Some(Spec::Todo));
        assert_eq!(ops.insert, Some(Spec::Todo));
        assert_eq!(ops.update, Some(Spec::Todo));
        assert_eq!(ops.delete, Some(Spec::Todo));
    }

    let test = db.rlsspec(&["test", "-c", spec_arg]);
    assert_eq!(test.code, Some(0), "{}", test.stderr);
    assert!(
        test.stdout
            .starts_with("coverage 0/32 cells (0.0%) · 32 unspecified (warn)\n"),
        "{}",
        test.stdout
    );
    assert!(
        test.stdout
            .ends_with("0 failed · 0 passed · 0 inconclusive\n")
    );
    assert_eq!(test.stdout.matches('○').count(), 8, "{}", test.stdout);
}

#[test]
fn init_refuses_to_overwrite_without_force() {
    let db = example_db(&[]);
    let spec = scratch("init_force").join("rlsspec.yaml");
    let spec_arg = spec.to_str().unwrap();
    fs::write(&spec, "keep me\n").unwrap();

    let out = db.rlsspec(&["init", "-o", spec_arg]);
    assert_eq!(out.code, Some(2));
    assert_eq!(
        out.stderr,
        format!("error: {spec_arg} already exists; pass --force to overwrite it\n")
    );
    assert_eq!(fs::read_to_string(&spec).unwrap(), "keep me\n");

    let out = db.rlsspec(&["init", "-o", spec_arg, "--force"]);
    assert_eq!(out.code, Some(0), "{}", out.stderr);
    assert!(
        fs::read_to_string(&spec)
            .unwrap()
            .starts_with("# Generated by `rlsspec init`")
    );
}
