use std::fmt::Write as _;
use std::fs::{File, OpenOptions};
use std::io::{self, Write as _};
use std::path::{Path, PathBuf};

use postgres::Transaction;

use crate::catalog;
use crate::config::Safety;
use crate::pg::{self, PgError, Session};

#[derive(Debug, thiserror::Error)]
pub enum InitError {
    #[error(transparent)]
    Pg(#[from] PgError),
    #[error("no tables found in {}", schemas_phrase(.0))]
    NoTables(Vec<String>),
    #[error(
        "no role other than PUBLIC holds a privilege on the tables in {}; grant privileges to the application roles first",
        schemas_phrase(.0)
    )]
    NoRoles(Vec<String>),
    #[error("{} already exists; pass --force to overwrite it", .0.display())]
    Exists(PathBuf),
    #[error("cannot write {}", path.display())]
    Write {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
}

impl From<postgres::Error> for InitError {
    fn from(err: postgres::Error) -> Self {
        Self::Pg(PgError::Query(err))
    }
}

/// What `init` found in the database: the tables in scope and the roles to scaffold identities from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Scaffold {
    pub schemas: Vec<String>,
    pub tables: Vec<String>,
    pub identities: Vec<String>,
    pub left_out: Vec<(String, &'static str)>,
}

impl Scaffold {
    pub fn cells(&self) -> usize {
        self.tables.len() * self.identities.len() * 4
    }
}

// Table and column grants (column ones included: `GRANT UPDATE (name)` is a privilege on the table).
const ROLES: &str = "
WITH grants AS (
    SELECT c.relowner, a.grantee
    FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) a
    WHERE c.oid = ANY($1)
    UNION ALL
    SELECT c.relowner, a.grantee
    FROM pg_class c
    JOIN pg_attribute att ON att.attrelid = c.oid AND att.attnum > 0 AND NOT att.attisdropped
    CROSS JOIN LATERAL aclexplode(att.attacl) a
    WHERE c.oid = ANY($1)
)
SELECT r.rolname::text, r.rolsuper, r.rolbypassrls, bool_and(g.grantee = g.relowner)
FROM grants g
JOIN pg_roles r ON r.oid = g.grantee
WHERE g.grantee <> 0
GROUP BY r.rolname, r.rolsuper, r.rolbypassrls
ORDER BY 1";

/// Reads the tables in `schemas` and the roles holding privileges on them, in a rolled-back transaction.
pub fn introspect(url: &str, schemas: &[String]) -> Result<Scaffold, InitError> {
    let mut client = pg::connect(url)?;
    let mut session = Session::begin(&mut client, &Safety::default())?;
    let scaffold = scaffold(session.tx(), schemas)?;
    session.rollback()?;
    if scaffold.tables.is_empty() {
        return Err(InitError::NoTables(schemas.to_vec()));
    }
    if scaffold.identities.is_empty() {
        return Err(InitError::NoRoles(schemas.to_vec()));
    }
    Ok(scaffold)
}

fn scaffold(tx: &mut Transaction, schemas: &[String]) -> Result<Scaffold, InitError> {
    let catalog = catalog::load(tx, schemas)?;
    let mut left_out = Vec::new();
    let mut tables = Vec::new();
    for table in catalog.tables() {
        // A spec reads `a.b` as schema `a`, table `b`: such a name can't be written yet.
        if table.name.contains('.') {
            left_out.push((
                format!("table {}.{}", table.schema, table.name),
                "its name contains a dot, which a spec can't express yet",
            ));
        } else {
            tables.push(catalog.display_name(table));
        }
    }
    let oids: Vec<u32> = catalog.tables().iter().map(|t| t.oid).collect();
    let mut identities = Vec::new();
    for row in tx.query(ROLES, &[&oids])? {
        let role: String = row.get(0);
        let reason = if row.get(1) {
            "superuser, so no policy applies to it"
        } else if row.get(2) {
            "BYPASSRLS, so no policy applies to it"
        } else if row.get(3) {
            "holds privileges only as the owner of the tables"
        } else {
            identities.push(role);
            continue;
        };
        left_out.push((format!("role {role}"), reason));
    }
    Ok(Scaffold {
        schemas: schemas.to_vec(),
        tables,
        identities,
        left_out,
    })
}

/// The spec file: valid as is, with every identity × table × operation cell `todo`.
pub fn render(scaffold: &Scaffold) -> String {
    let schemas = scaffold
        .schemas
        .iter()
        .map(|s| scalar(s))
        .collect::<Vec<_>>()
        .join(", ");
    let mut out = format!(
        "# Generated by `rlsspec init` from {}.
# Every identity × table × operation is `todo`: replace each one with the access you intend, e.g.
# `select: deny`, `select: {{ rows: \"published\" }}` or `update: [{{ where: \"true\", expect: deny }}]`.
# `rlsspec cover` shows what is left; `rlsspec test` runs what is specified.
version: 1

database:
  url: ${{env:DATABASE_URL}}
  schemas: [{schemas}]

# setup:                          # SQL files run first as the privileged role, always rolled back
#   - seed.sql                    # (the rows your checks need)

",
        schemas_phrase(&scaffold.schemas)
    );

    out.push_str(
        "# One identity per role holding a privilege on a table in scope (PUBLIC excluded).\n",
    );
    if !scaffold.left_out.is_empty() {
        out.push_str("# Left out:\n");
        for (what, reason) in &scaffold.left_out {
            let _ = writeln!(out, "#   {what}: {reason}");
        }
    }
    out.push_str("identities:\n");
    for role in &scaffold.identities {
        let name = scalar(role);
        let _ = writeln!(
            out,
            "  {name}:\n    role: {name}\n    # TODO: gucs, the session settings your policies read, e.g. gucs: {{ app.user_id: \"…\" }}"
        );
    }

    out.push_str(
        "
# Cells without a case are listed as unspecified. Use `fail` in CI once the spec is complete.
unspecified: warn

expect:
",
    );
    for table in &scaffold.tables {
        let _ = writeln!(out, "  {}:", scalar(table));
        for role in &scaffold.identities {
            let _ = writeln!(
                out,
                "    {}: {{ select: todo, insert: todo, update: todo, delete: todo }}",
                scalar(role)
            );
        }
    }
    out
}

/// Writes `text` to `path`, never replacing an existing file unless `force`.
pub fn write(path: &Path, text: &str, force: bool) -> Result<(), InitError> {
    let file = if force {
        File::create(path)
    } else {
        OpenOptions::new().write(true).create_new(true).open(path)
    };
    let failed = |source: io::Error| match source.kind() {
        io::ErrorKind::AlreadyExists => InitError::Exists(path.to_path_buf()),
        _ => InitError::Write {
            path: path.to_path_buf(),
            source,
        },
    };
    file.and_then(|mut f| f.write_all(text.as_bytes()))
        .map_err(failed)
}

fn schemas_phrase(schemas: &[String]) -> String {
    let noun = if schemas.len() == 1 {
        "schema"
    } else {
        "schemas"
    };
    format!("{noun} {}", schemas.join(", "))
}

/// A YAML scalar for a name: plain when that can't be misread, double-quoted otherwise.
fn scalar(name: &str) -> String {
    const RESERVED: [&str; 9] = ["true", "false", "yes", "no", "on", "off", "y", "n", "null"];
    let mut chars = name.chars();
    let plain = chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.'))
        && !RESERVED.contains(&name.to_ascii_lowercase().as_str());
    if plain {
        return name.to_owned();
    }
    let mut out = String::from("\"");
    for c in name.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if c.is_control() => {
                let _ = write!(out, "\\u{:04x}", u32::from(c));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;
    use crate::config::{self, Spec};

    fn example() -> Scaffold {
        Scaffold {
            schemas: vec!["public".into()],
            tables: vec!["notes".into(), "Weird Table".into()],
            identities: vec!["app".into(), "on".into(), "we\"ird".into()],
            left_out: vec![(
                "role postgres".into(),
                "superuser, so no policy applies to it",
            )],
        }
    }

    #[test]
    fn names_are_quoted_when_needed() {
        assert_eq!(scalar("app_user"), "app_user");
        assert_eq!(scalar("app.notes"), "app.notes");
        assert_eq!(scalar("Off"), "\"Off\"");
        assert_eq!(scalar("9lives"), "\"9lives\"");
        assert_eq!(scalar("a b"), "\"a b\"");
        assert_eq!(scalar("we\"ird\\"), "\"we\\\"ird\\\\\"");
    }

    #[test]
    fn rendered_spec_round_trips_with_every_cell_todo() {
        let text = render(&example());
        let env = |name: &str| (name == "DATABASE_URL").then(|| "postgres://localhost/db".into());
        let config = config::parse(&text, Path::new("rlsspec.yaml"), &env).unwrap();
        let identities: Vec<_> = config.identities.iter().map(|i| i.role.as_str()).collect();
        assert_eq!(identities, ["app", "on", "we\"ird"]);
        assert_eq!(config.expect.len(), 6);
        for block in &config.expect {
            let ops = &block.ops;
            assert_eq!(ops.select, Some(Spec::Todo));
            assert_eq!(ops.insert, Some(Spec::Todo));
            assert_eq!(ops.update, Some(Spec::Todo));
            assert_eq!(ops.delete, Some(Spec::Todo));
        }
    }
}
